baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "MuchuBlog"
theme = "hugo.386"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Muchu-Blog"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to my personal internet space." 

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Stuff that goes through my head"
    url = "/thoughts/"
    weight = 20

  [[menu.main]]
    name = "Muchu's Bizarre Misadventures"
    url = "/bizarre/"
    weight = 30

  [[menu.main]]
    name = "Taste in Media"
    url = "/media/"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50